# Generated by Django 4.0.6 on 2022-09-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=400)),
                ('subtitulo', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=400)),
                ('foto', models.ImageField(upload_to='images')),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
