# Generated by Django 4.0.6 on 2022-10-11 09:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
